version: "3.9"

services:
  db:
    image: mysql:lts
    container_name: db
    env_file:
      - ./backend/.env
    networks:
      - chattingo
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    image: virajdalave/chattingo-app:latest
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    networks:
      - chattingo

  frontend:
    image: virajdalave/chattingo-web:latest
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - chattingo

volumes:
  db_data:

networks:
  chattingo:
    driver: bridge
